package main

type WeatherStation struct {
	Id   string
	Temp float64
}

// data from https://en.wikipedia.org/wiki/List_of_cities_by_average_temperature;
var stations = []WeatherStation{
	{Id: "Abha", Temp: 18.0},
	{Id: "Abidjan", Temp: 26.0},
	{Id: "Abéché", Temp: 29.4},
	{Id: "Accra", Temp: 26.4},
	{Id: "Addis Ababa", Temp: 16.0},
	{Id: "Adelaide", Temp: 17.3},
	{Id: "Aden", Temp: 29.1},
	{Id: "Ahvaz", Temp: 25.4},
	{Id: "Albuquerque", Temp: 14.0},
	{Id: "Alexandra", Temp: 11.0},
	{Id: "Alexandria", Temp: 20.0},
	{Id: "Algiers", Temp: 18.2},
	{Id: "Alice Springs", Temp: 21.0},
	{Id: "Almaty", Temp: 10.0},
	{Id: "Amsterdam", Temp: 10.2},
	{Id: "Anadyr", Temp: -6.9},
	{Id: "Anchorage", Temp: 2.8},
	{Id: "Andorra la Vella", Temp: 9.8},
	{Id: "Ankara", Temp: 12.0},
	{Id: "Antananarivo", Temp: 17.9},
	{Id: "Antsiranana", Temp: 25.2},
	{Id: "Arkhangelsk", Temp: 1.3},
	{Id: "Ashgabat", Temp: 17.1},
	{Id: "Asmara", Temp: 15.6},
	{Id: "Assab", Temp: 30.5},
	{Id: "Astana", Temp: 3.5},
	{Id: "Athens", Temp: 19.2},
	{Id: "Atlanta", Temp: 17.0},
	{Id: "Auckland", Temp: 15.2},
	{Id: "Austin", Temp: 20.7},
	{Id: "Baghdad", Temp: 22.77},
	{Id: "Baguio", Temp: 19.5},
	{Id: "Baku", Temp: 15.1},
	{Id: "Baltimore", Temp: 13.1},
	{Id: "Bamako", Temp: 27.8},
	{Id: "Bangkok", Temp: 28.6},
	{Id: "Bangui", Temp: 26.0},
	{Id: "Banjul", Temp: 26.0},
	{Id: "Barcelona", Temp: 18.2},
	{Id: "Bata", Temp: 25.1},
	{Id: "Batumi", Temp: 14.0},
	{Id: "Beijing", Temp: 12.9},
	{Id: "Beirut", Temp: 20.9},
	{Id: "Belgrade", Temp: 12.5},
	{Id: "Belize City", Temp: 26.7},
	{Id: "Benghazi", Temp: 19.9},
	{Id: "Bergen", Temp: 7.7},
	{Id: "Berlin", Temp: 10.3},
	{Id: "Bilbao", Temp: 14.7},
	{Id: "Birao", Temp: 26.5},
	{Id: "Bishkek", Temp: 11.3},
	{Id: "Bissau", Temp: 27.0},
	{Id: "Blantyre", Temp: 22.2},
	{Id: "Bloemfontein", Temp: 15.6},
	{Id: "Boise", Temp: 11.4},
	{Id: "Bordeaux", Temp: 14.2},
	{Id: "Bosaso", Temp: 30.0},
	{Id: "Boston", Temp: 10.9},
	{Id: "Bouaké", Temp: 26.0},
	{Id: "Bratislava", Temp: 10.5},
	{Id: "Brazzaville", Temp: 25.0},
	{Id: "Bridgetown", Temp: 27.0},
	{Id: "Brisbane", Temp: 21.4},
	{Id: "Brussels", Temp: 10.5},
	{Id: "Bucharest", Temp: 10.8},
	{Id: "Budapest", Temp: 11.3},
	{Id: "Bujumbura", Temp: 23.8},
	{Id: "Bulawayo", Temp: 18.9},
	{Id: "Burnie", Temp: 13.1},
	{Id: "Busan", Temp: 15.0},
	{Id: "Cabo San Lucas", Temp: 23.9},
	{Id: "Cairns", Temp: 25.0},
	{Id: "Cairo", Temp: 21.4},
	{Id: "Calgary", Temp: 4.4},
	{Id: "Canberra", Temp: 13.1},
	{Id: "Cape Town", Temp: 16.2},
	{Id: "Changsha", Temp: 17.4},
	{Id: "Charlotte", Temp: 16.1},
	{Id: "Chiang Mai", Temp: 25.8},
	{Id: "Chicago", Temp: 9.8},
	{Id: "Chihuahua", Temp: 18.6},
	{Id: "Chișinău", Temp: 10.2},
	{Id: "Chittagong", Temp: 25.9},
	{Id: "Chongqing", Temp: 18.6},
	{Id: "Christchurch", Temp: 12.2},
	{Id: "City of San Marino", Temp: 11.8},
	{Id: "Colombo", Temp: 27.4},
	{Id: "Columbus", Temp: 11.7},
	{Id: "Conakry", Temp: 26.4},
	{Id: "Copenhagen", Temp: 9.1},
	{Id: "Cotonou", Temp: 27.2},
	{Id: "Cracow", Temp: 9.3},
	{Id: "Da Lat", Temp: 17.9},
	{Id: "Da Nang", Temp: 25.8},
	{Id: "Dakar", Temp: 24.0},
	{Id: "Dallas", Temp: 19.0},
	{Id: "Damascus", Temp: 17.0},
	{Id: "Dampier", Temp: 26.4},
	{Id: "Dar es Salaam", Temp: 25.8},
	{Id: "Darwin", Temp: 27.6},
	{Id: "Denpasar", Temp: 23.7},
	{Id: "Denver", Temp: 10.4},
	{Id: "Detroit", Temp: 10.0},
	{Id: "Dhaka", Temp: 25.9},
	{Id: "Dikson", Temp: -11.1},
	{Id: "Dili", Temp: 26.6},
	{Id: "Djibouti", Temp: 29.9},
	{Id: "Dodoma", Temp: 22.7},
	{Id: "Dolisie", Temp: 24.0},
	{Id: "Douala", Temp: 26.7},
	{Id: "Dubai", Temp: 26.9},
	{Id: "Dublin", Temp: 9.8},
	{Id: "Dunedin", Temp: 11.1},
	{Id: "Durban", Temp: 20.6},
	{Id: "Dushanbe", Temp: 14.7},
	{Id: "Edinburgh", Temp: 9.3},
	{Id: "Edmonton", Temp: 4.2},
	{Id: "El Paso", Temp: 18.1},
	{Id: "Entebbe", Temp: 21.0},
	{Id: "Erbil", Temp: 19.5},
	{Id: "Erzurum", Temp: 5.1},
	{Id: "Fairbanks", Temp: -2.3},
	{Id: "Fianarantsoa", Temp: 17.9},
	{Id: "Flores,  Petén", Temp: 26.4},
	{Id: "Frankfurt", Temp: 10.6},
	{Id: "Fresno", Temp: 17.9},
	{Id: "Fukuoka", Temp: 17.0},
	{Id: "Gabès", Temp: 19.5},
	{Id: "Gaborone", Temp: 21.0},
	{Id: "Gagnoa", Temp: 26.0},
	{Id: "Gangtok", Temp: 15.2},
	{Id: "Garissa", Temp: 29.3},
	{Id: "Garoua", Temp: 28.3},
	{Id: "George Town", Temp: 27.9},
	{Id: "Ghanzi", Temp: 21.4},
	{Id: "Gjoa Haven", Temp: -14.4},
	{Id: "Guadalajara", Temp: 20.9},
	{Id: "Guangzhou", Temp: 22.4},
	{Id: "Guatemala City", Temp: 20.4},
	{Id: "Halifax", Temp: 7.5},
	{Id: "Hamburg", Temp: 9.7},
	{Id: "Hamilton", Temp: 13.8},
	{Id: "Hanga Roa", Temp: 20.5},
	{Id: "Hanoi", Temp: 23.6},
	{Id: "Harare", Temp: 18.4},
	{Id: "Harbin", Temp: 5.0},
	{Id: "Hargeisa", Temp: 21.7},
	{Id: "Hat Yai", Temp: 27.0},
	{Id: "Havana", Temp: 25.2},
	{Id: "Helsinki", Temp: 5.9},
	{Id: "Heraklion", Temp: 18.9},
	{Id: "Hiroshima", Temp: 16.3},
	{Id: "Ho Chi Minh City", Temp: 27.4},
	{Id: "Hobart", Temp: 12.7},
	{Id: "Hong Kong", Temp: 23.3},
	{Id: "Honiara", Temp: 26.5},
	{Id: "Honolulu", Temp: 25.4},
	{Id: "Houston", Temp: 20.8},
	{Id: "Ifrane", Temp: 11.4},
	{Id: "Indianapolis", Temp: 11.8},
	{Id: "Iqaluit", Temp: -9.3},
	{Id: "Irkutsk", Temp: 1.0},
	{Id: "Istanbul", Temp: 13.9},
	{Id: "İzmir", Temp: 17.9},
	{Id: "Jacksonville", Temp: 20.3},
	{Id: "Jakarta", Temp: 26.7},
	{Id: "Jayapura", Temp: 27.0},
	{Id: "Jerusalem", Temp: 18.3},
	{Id: "Johannesburg", Temp: 15.5},
	{Id: "Jos", Temp: 22.8},
	{Id: "Juba", Temp: 27.8},
	{Id: "Kabul", Temp: 12.1},
	{Id: "Kampala", Temp: 20.0},
	{Id: "Kandi", Temp: 27.7},
	{Id: "Kankan", Temp: 26.5},
	{Id: "Kano", Temp: 26.4},
	{Id: "Kansas City", Temp: 12.5},
	{Id: "Karachi", Temp: 26.0},
	{Id: "Karonga", Temp: 24.4},
	{Id: "Kathmandu", Temp: 18.3},
	{Id: "Khartoum", Temp: 29.9},
	{Id: "Kingston", Temp: 27.4},
	{Id: "Kinshasa", Temp: 25.3},
	{Id: "Kolkata", Temp: 26.7},
	{Id: "Kuala Lumpur", Temp: 27.3},
	{Id: "Kumasi", Temp: 26.0},
	{Id: "Kunming", Temp: 15.7},
	{Id: "Kuopio", Temp: 3.4},
	{Id: "Kuwait City", Temp: 25.7},
	{Id: "Kyiv", Temp: 8.4},
	{Id: "Kyoto", Temp: 15.8},
	{Id: "La Ceiba", Temp: 26.2},
	{Id: "La Paz", Temp: 23.7},
	{Id: "Lagos", Temp: 26.8},
	{Id: "Lahore", Temp: 24.3},
	{Id: "Lake Havasu City", Temp: 23.7},
	{Id: "Lake Tekapo", Temp: 8.7},
	{Id: "Las Palmas de Gran Canaria", Temp: 21.2},
	{Id: "Las Vegas", Temp: 20.3},
	{Id: "Launceston", Temp: 13.1},
	{Id: "Lhasa", Temp: 7.6},
	{Id: "Libreville", Temp: 25.9},
	{Id: "Lisbon", Temp: 17.5},
	{Id: "Livingstone", Temp: 21.8},
	{Id: "Ljubljana", Temp: 10.9},
	{Id: "Lodwar", Temp: 29.3},
	{Id: "Lomé", Temp: 26.9},
	{Id: "London", Temp: 11.3},
	{Id: "Los Angeles", Temp: 18.6},
	{Id: "Louisville", Temp: 13.9},
	{Id: "Luanda", Temp: 25.8},
	{Id: "Lubumbashi", Temp: 20.8},
	{Id: "Lusaka", Temp: 19.9},
	{Id: "Luxembourg City", Temp: 9.3},
	{Id: "Lviv", Temp: 7.8},
	{Id: "Lyon", Temp: 12.5},
	{Id: "Madrid", Temp: 15.0},
	{Id: "Mahajanga", Temp: 26.3},
	{Id: "Makassar", Temp: 26.7},
	{Id: "Makurdi", Temp: 26.0},
	{Id: "Malabo", Temp: 26.3},
	{Id: "Malé", Temp: 28.0},
	{Id: "Managua", Temp: 27.3},
	{Id: "Manama", Temp: 26.5},
	{Id: "Mandalay", Temp: 28.0},
	{Id: "Mango", Temp: 28.1},
	{Id: "Manila", Temp: 28.4},
	{Id: "Maputo", Temp: 22.8},
	{Id: "Marrakesh", Temp: 19.6},
	{Id: "Marseille", Temp: 15.8},
	{Id: "Maun", Temp: 22.4},
	{Id: "Medan", Temp: 26.5},
	{Id: "Mek'ele", Temp: 22.7},
	{Id: "Melbourne", Temp: 15.1},
	{Id: "Memphis", Temp: 17.2},
	{Id: "Mexicali", Temp: 23.1},
	{Id: "Mexico City", Temp: 17.5},
	{Id: "Miami", Temp: 24.9},
	{Id: "Milan", Temp: 13.0},
	{Id: "Milwaukee", Temp: 8.9},
	{Id: "Minneapolis", Temp: 7.8},
	{Id: "Minsk", Temp: 6.7},
	{Id: "Mogadishu", Temp: 27.1},
	{Id: "Mombasa", Temp: 26.3},
	{Id: "Monaco", Temp: 16.4},
	{Id: "Moncton", Temp: 6.1},
	{Id: "Monterrey", Temp: 22.3},
	{Id: "Montreal", Temp: 6.8},
	{Id: "Moscow", Temp: 5.8},
	{Id: "Mumbai", Temp: 27.1},
	{Id: "Murmansk", Temp: 0.6},
	{Id: "Muscat", Temp: 28.0},
	{Id: "Mzuzu", Temp: 17.7},
	{Id: "N'Djamena", Temp: 28.3},
	{Id: "Naha", Temp: 23.1},
	{Id: "Nairobi", Temp: 17.8},
	{Id: "Nakhon Ratchasima", Temp: 27.3},
	{Id: "Napier", Temp: 14.6},
	{Id: "Napoli", Temp: 15.9},
	{Id: "Nashville", Temp: 15.4},
	{Id: "Nassau", Temp: 24.6},
	{Id: "Ndola", Temp: 20.3},
	{Id: "New Delhi", Temp: 25.0},
	{Id: "New Orleans", Temp: 20.7},
	{Id: "New York City", Temp: 12.9},
	{Id: "Ngaoundéré", Temp: 22.0},
	{Id: "Niamey", Temp: 29.3},
	{Id: "Nicosia", Temp: 19.7},
	{Id: "Niigata", Temp: 13.9},
	{Id: "Nouadhibou", Temp: 21.3},
	{Id: "Nouakchott", Temp: 25.7},
	{Id: "Novosibirsk", Temp: 1.7},
	{Id: "Nuuk", Temp: -1.4},
	{Id: "Odesa", Temp: 10.7},
	{Id: "Odienné", Temp: 26.0},
	{Id: "Oklahoma City", Temp: 15.9},
	{Id: "Omaha", Temp: 10.6},
	{Id: "Oranjestad", Temp: 28.1},
	{Id: "Oslo", Temp: 5.7},
	{Id: "Ottawa", Temp: 6.6},
	{Id: "Ouagadougou", Temp: 28.3},
	{Id: "Ouahigouya", Temp: 28.6},
	{Id: "Ouarzazate", Temp: 18.9},
	{Id: "Oulu", Temp: 2.7},
	{Id: "Palembang", Temp: 27.3},
	{Id: "Palermo", Temp: 18.5},
	{Id: "Palm Springs", Temp: 24.5},
	{Id: "Palmerston North", Temp: 13.2},
	{Id: "Panama City", Temp: 28.0},
	{Id: "Parakou", Temp: 26.8},
	{Id: "Paris", Temp: 12.3},
	{Id: "Perth", Temp: 18.7},
	{Id: "Petropavlovsk-Kamchatsky", Temp: 1.9},
	{Id: "Philadelphia", Temp: 13.2},
	{Id: "Phnom Penh", Temp: 28.3},
	{Id: "Phoenix", Temp: 23.9},
	{Id: "Pittsburgh", Temp: 10.8},
	{Id: "Podgorica", Temp: 15.3},
	{Id: "Pointe-Noire", Temp: 26.1},
	{Id: "Pontianak", Temp: 27.7},
	{Id: "Port Moresby", Temp: 26.9},
	{Id: "Port Sudan", Temp: 28.4},
	{Id: "Port Vila", Temp: 24.3},
	{Id: "Port-Gentil", Temp: 26.0},
	{Id: "Portland (OR)", Temp: 12.4},
	{Id: "Porto", Temp: 15.7},
	{Id: "Prague", Temp: 8.4},
	{Id: "Praia", Temp: 24.4},
	{Id: "Pretoria", Temp: 18.2},
	{Id: "Pyongyang", Temp: 10.8},
	{Id: "Rabat", Temp: 17.2},
	{Id: "Rangpur", Temp: 24.4},
	{Id: "Reggane", Temp: 28.3},
	{Id: "Reykjavík", Temp: 4.3},
	{Id: "Riga", Temp: 6.2},
	{Id: "Riyadh", Temp: 26.0},
	{Id: "Rome", Temp: 15.2},
	{Id: "Roseau", Temp: 26.2},
	{Id: "Rostov-on-Don", Temp: 9.9},
	{Id: "Sacramento", Temp: 16.3},
	{Id: "Saint Petersburg", Temp: 5.8},
	{Id: "Saint-Pierre", Temp: 5.7},
	{Id: "Salt Lake City", Temp: 11.6},
	{Id: "San Antonio", Temp: 20.8},
	{Id: "San Diego", Temp: 17.8},
	{Id: "San Francisco", Temp: 14.6},
	{Id: "San Jose", Temp: 16.4},
	{Id: "San José", Temp: 22.6},
	{Id: "San Juan", Temp: 27.2},
	{Id: "San Salvador", Temp: 23.1},
	{Id: "Sana'a", Temp: 20.0},
	{Id: "Santo Domingo", Temp: 25.9},
	{Id: "Sapporo", Temp: 8.9},
	{Id: "Sarajevo", Temp: 10.1},
	{Id: "Saskatoon", Temp: 3.3},
	{Id: "Seattle", Temp: 11.3},
	{Id: "Ségou", Temp: 28.0},
	{Id: "Seoul", Temp: 12.5},
	{Id: "Seville", Temp: 19.2},
	{Id: "Shanghai", Temp: 16.7},
	{Id: "Singapore", Temp: 27.0},
	{Id: "Skopje", Temp: 12.4},
	{Id: "Sochi", Temp: 14.2},
	{Id: "Sofia", Temp: 10.6},
	{Id: "Sokoto", Temp: 28.0},
	{Id: "Split", Temp: 16.1},
	{Id: "St. John's", Temp: 5.0},
	{Id: "St. Louis", Temp: 13.9},
	{Id: "Stockholm", Temp: 6.6},
	{Id: "Surabaya", Temp: 27.1},
	{Id: "Suva", Temp: 25.6},
	{Id: "Suwałki", Temp: 7.2},
	{Id: "Sydney", Temp: 17.7},
	{Id: "Tabora", Temp: 23.0},
	{Id: "Tabriz", Temp: 12.6},
	{Id: "Taipei", Temp: 23.0},
	{Id: "Tallinn", Temp: 6.4},
	{Id: "Tamale", Temp: 27.9},
	{Id: "Tamanrasset", Temp: 21.7},
	{Id: "Tampa", Temp: 22.9},
	{Id: "Tashkent", Temp: 14.8},
	{Id: "Tauranga", Temp: 14.8},
	{Id: "Tbilisi", Temp: 12.9},
	{Id: "Tegucigalpa", Temp: 21.7},
	{Id: "Tehran", Temp: 17.0},
	{Id: "Tel Aviv", Temp: 20.0},
	{Id: "Thessaloniki", Temp: 16.0},
	{Id: "Thiès", Temp: 24.0},
	{Id: "Tijuana", Temp: 17.8},
	{Id: "Timbuktu", Temp: 28.0},
	{Id: "Tirana", Temp: 15.2},
	{Id: "Toamasina", Temp: 23.4},
	{Id: "Tokyo", Temp: 15.4},
	{Id: "Toliara", Temp: 24.1},
	{Id: "Toluca", Temp: 12.4},
	{Id: "Toronto", Temp: 9.4},
	{Id: "Tripoli", Temp: 20.0},
	{Id: "Tromsø", Temp: 2.9},
	{Id: "Tucson", Temp: 20.9},
	{Id: "Tunis", Temp: 18.4},
	{Id: "Ulaanbaatar", Temp: -0.4},
	{Id: "Upington", Temp: 20.4},
	{Id: "Ürümqi", Temp: 7.4},
	{Id: "Vaduz", Temp: 10.1},
	{Id: "Valencia", Temp: 18.3},
	{Id: "Valletta", Temp: 18.8},
	{Id: "Vancouver", Temp: 10.4},
	{Id: "Veracruz", Temp: 25.4},
	{Id: "Vienna", Temp: 10.4},
	{Id: "Vientiane", Temp: 25.9},
	{Id: "Villahermosa", Temp: 27.1},
	{Id: "Vilnius", Temp: 6.0},
	{Id: "Virginia Beach", Temp: 15.8},
	{Id: "Vladivostok", Temp: 4.9},
	{Id: "Warsaw", Temp: 8.5},
	{Id: "Washington, D.C.", Temp: 14.6},
	{Id: "Wau", Temp: 27.8},
	{Id: "Wellington", Temp: 12.9},
	{Id: "Whitehorse", Temp: -0.1},
	{Id: "Wichita", Temp: 13.9},
	{Id: "Willemstad", Temp: 28.0},
	{Id: "Winnipeg", Temp: 3.0},
	{Id: "Wrocław", Temp: 9.6},
	{Id: "Xi'an", Temp: 14.1},
	{Id: "Yakutsk", Temp: -8.8},
	{Id: "Yangon", Temp: 27.5},
	{Id: "Yaoundé", Temp: 23.8},
	{Id: "Yellowknife", Temp: -4.3},
	{Id: "Yerevan", Temp: 12.4},
	{Id: "Yinchuan", Temp: 9.0},
	{Id: "Zagreb", Temp: 10.7},
	{Id: "Zanzibar City", Temp: 26.0},
	{Id: "Zürich", Temp: 9.3},
}
